### ISSUE TITLE
Weird bug in Higher Rank Trait Bounds resolutions

### ISSUE THREAD

**Issue by hhirtz** [vbarrielle/sprs#295]
Stumbled on a weird compilation error triggered by sprs "presence"  (??).

The following project fails to build unless `extern crate sprs` is commented: https://github.com/hhirtz/sprs-hrtb-bug/blob/master/src/lib.rs

Of course the compilation error does not come from this line: it will appear if sprs is used elsewhere in the cargo project. (e.g. you can replace "extern crate" with `type Hi = sprs::CsMatView<'static, u32>;` to trigger the error).

```
cargo 1.55.0 (32da73ab1 2021-08-23)
```

**Comment by hhirtz** [comment]
sprs 0.9.0 works fine

**Comment by hhirtz** [comment]
https://github.com/vbarrielle/sprs/commit/d2f0da76df51be6e81839b04ed64c5121a2ec640 is the first bad commit

**Comment by hhirtz** [comment]
Might be related to https://github.com/rust-lang/rust/issues/85063
